# Generated by Django 5.0.1 on 2024-01-07 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('address', models.TextField()),
                ('idproff', models.CharField(max_length=200)),
                ('idtype', models.CharField(max_length=100)),
                ('contactno', models.BigIntegerField()),
                ('emer_contactno', models.BigIntegerField()),
                ('deliverdate', models.DateField()),
                ('delivertime', models.CharField(max_length=10)),
                ('deliverymode', models.CharField(max_length=100)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bloodstock')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
