# Generated by Django 5.0.1 on 2024-01-08 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_orderdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offlinedelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('delivery_address', models.TextField()),
                ('message', models.TextField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
